CREATE TABLE CUSTOMER
(
ID INT PRIMARY KEY,
NAME VARCHAR(25) NOT NULL,
AGE INT NOT NULL
);

INSERT INTO CUSTOMER VALUES(101,'RAHUL',22);
INSERT INTO CUSTOMER VALUES(102,'MEHUL',24);
INSERT INTO CUSTOMER VALUES(103,'KEYUR',23);
INSERT INTO CUSTOMER VALUES(104,'TEJ',35);
INSERT INTO CUSTOMER VALUES(105,'YASH',18);

SELECT * FROM CUSTOMER;

CREATE TABLE ORDERS
(
ID INT NOT NULL,
ORDER_ID INT NOT NULL,
ORDER_NUMBER INT NOT NULL,
FOREIGN KEY (ID) REFERENCES CUSTOMER(ID)
);

INSERT INTO ORDERS VALUES(101,123456,1);
INSERT INTO ORDERS VALUES(101,123457,2);
INSERT INTO ORDERS VALUES(102,123458,3);
INSERT INTO ORDERS VALUES(104,123459,4);
INSERT INTO ORDERS VALUES(104,123454,5);

SELECT * FROM ORDERS;

SELECT * FROM CUSTOMER
NATURAL JOIN ORDERS;

SELECT CUSTOMER.ID,CUSTOMER.NAME,ORDERS.ORDER_ID,ORDERS.ORDER_NUMBER
FROM CUSTOMER LEFT JOIN
ORDERS ON CUSTOMER.ID=ORDERS.ID;

SELECT CUSTOMER.ID,CUSTOMER.NAME,ORDERS.ORDER_ID,ORDERS.ORDER_NUMBER
FROM CUSTOMER RIGHT JOIN
ORDERS ON CUSTOMER.ID=ORDERS.ID;

SELECT CUSTOMER.ID,CUSTOMER.NAME,ORDERS.ORDER_ID,ORDERS.ORDER_NUMBER
FROM ORDERS INNER JOIN
CUSTOMER ON CUSTOMER.ID=ORDERS.ID;

SELECT * FROM CUSTOMER 
CROSS JOIN ORDERS;

SELECT * FROM CUSTOMER
UNION
SELECT * FROM ORDERS;